In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#membuat dataframe dengan list
list1 = ['berenang','bersepeda','mendaki']
list2 = [50000,0,15000]

comp = list(zip(list1, list2)) #mengelompokkan list berdasarkan index

pd.DataFrame(comp, columns=['hobi','harga'])

        hobi  harga
0   berenang  50000
1  bersepeda      0
2    mendaki  15000

In [ ]:
list2[1] = 1000 #bisa dimanipulasi

In [ ]:
list2

[50000, 1000, 15000]

In [ ]:
#membuat dataframe dengan tuple, perhatikan bedanya dengan list
tuple1 = ('Machine Learning',2)
tuple2 = ('Marketing',2)
tuple3 = ('Products',1)

pd.DataFrame([tuple1, tuple2, tuple3], columns=['pengalaman', 'lamanya'])

         pengalaman  lamanya
0  Machine Learning        2
1         Marketing        2
2          Products        1

In [ ]:
tuple2[1]

2

In [ ]:

np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
#numpy array
arr = np.array([[1,'Ari','2021-01-01'],[1,1,1],[2,'b','c']])

nump_arr = pd.DataFrame(arr, columns=['Joki','Nama','Tanggal'])
nump_arr

  Joki Nama     Tanggal
0    1  Ari  2021-01-01
1    1    1           1
2    2    b           c

In [ ]:
arr

array([['1', 'Ari', '2021-01-01'],
       ['1', 'mang', '1'],
       ['2', 'b', 'c']], dtype='<U21')

In [ ]:
nump_arr.info() #kalo numpy semua data type nya akan berupa object, perlu di convert dulu

In [ ]:
nump_arr['Joki'] = nump_arr['Joki'].astype('int64')

In [ ]:
arr[1,1] ='mang'
arr

array([['1', 'Ari', '2021-01-01'],
       ['1', 'mang', '1'],
       ['2', 'b', 'c']], dtype='<U21')

In [ ]:
#pandas
series1 = pd.Series(['berenang','bersepeda','mendaki'])
series2 = pd.Series([50000,10000,15000])

pandas_pd = pd.DataFrame({'hobi':series1,'harga':series2})
pandas_pd

        hobi  harga
0   berenang  50000
1  bersepeda  10000
2    mendaki  15000

In [ ]:
pandas_pd.info()

In [ ]:
series1[2::-1]

2      mendaki
1    bersepeda
0     berenang
dtype: object

In [ ]:
#array dan pandas hanya bisa menyimpan 1 tipe data
#tapi bisa untuk input macam - macam tipe data, nanti akan tersimpan sebagai object

In [ ]:
#reading dataset
from google.colab import files

In [ ]:
 files.upload()

TypeError: ignored

In [ ]:
read_data = pd.read_csv('Book1.csv')
read_data.head()

   shopid  buyerid register_date country
0    2230     1024    12/10/2021      ID
1    2087     4678     9/19/2021      SZ
2    2830     2693      5/3/2019      SG
3    2812     3421    10/14/2020      MY
4    2532     3668     5/10/2020      MY

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
read.gdrive = pd.read_csv('link file di google drive')

In [ ]:
list1 = ['462809','462643','466315','461735']
list2 = ['Male','Female','Female','Male']
list3 = ['No','Yes','Yes','Yes']
list4 = [22,38,67,67]
list5 = ['No','Yes','Yes','Yes']
list6 = ['Healthcare', 'Engineer','Engineer','Lawyer']
list7 = ['1.0',' ','1.0','0.0']
list8 = ['Low','Average','Low','High']
list9 = [4.0,3.0,1.0,2.0]
list10 = ['Cat_4','Cat_4','Cat_6','Cat_6']
list11 = ['D','A','B','B']

comp = list(zip(list1, list2, list3, list4, list5, list6, list7, list8, list9, list10, list11)) 

data_list = pd.DataFrame(comp, columns=['ID','Gender','Ever_Married','Age','Graduated','Profession','Work_Experience','Spending_Score','Family_Size',
                                   'Var_1','Segmentation'])
data_list

       ID  Gender Ever_Married  ...  Family_Size  Var_1 Segmentation
0  462809    Male           No  ...          4.0  Cat_4            D
1  462643  Female          Yes  ...          3.0  Cat_4            A
2  466315  Female          Yes  ...          1.0  Cat_6            B
3  461735    Male          Yes  ...          2.0  Cat_6            B

[4 rows x 11 columns]

In [ ]:
tuple1 = ('462809','Male','No',22,'No','Healthcare','1.0','Low',4.0,'Cat_4','D')
tuple2 = ('462643','Female','Yes',38,'Yes','Engineer',' ','Average',3.0,'Cat_4','A')
tuple3 = ('466315','Female','Yes',67,'Yes','Engineer','1.0','Low',1.0,'Cat_6','B')
tuple4 = ('461735','Male','Yes',67,'Yes','Lawyer','0.0','High',2.0,'Cat_6','B')

data_tuple = pd.DataFrame([tuple1, tuple2, tuple3, tuple4], columns=['ID','Gender','Ever_Married','Age','Graduated','Profession','Work_Experience',
                                                                     'Spending_Score','Family_Size','Var_1','Segmentation'])
data_tuple

       ID  Gender Ever_Married  ...  Family_Size  Var_1 Segmentation
0  462809    Male           No  ...          4.0  Cat_4            D
1  462643  Female          Yes  ...          3.0  Cat_4            A
2  466315  Female          Yes  ...          1.0  Cat_6            B
3  461735    Male          Yes  ...          2.0  Cat_6            B

[4 rows x 11 columns]

In [ ]:
arr = np.array([['462809','Male','No',22,'No','Healthcare','1.0','Low',4.0,'Cat_4','D'],
                ['462643','Female','Yes',38,'Yes','Engineer',' ','Average',3.0,'Cat_4','A'],
                 ['466315','Female','Yes',67,'Yes','Engineer','1.0','Low',1.0,'Cat_6','B'],
                ['461735','Male','Yes',67,'Yes','Lawyer','0.0','High',2.0,'Cat_6','B']])

data_arr = pd.DataFrame(arr, columns=['ID','Gender','Ever_Married','Age','Graduated','Profession','Work_Experience',
                                                                     'Spending_Score','Family_Size','Var_1','Segmentation'])
data_arr

       ID  Gender Ever_Married  ... Family_Size  Var_1 Segmentation
0  462809    Male           No  ...         4.0  Cat_4            D
1  462643  Female          Yes  ...         3.0  Cat_4            A
2  466315  Female          Yes  ...         1.0  Cat_6            B
3  461735    Male          Yes  ...         2.0  Cat_6            B

[4 rows x 11 columns]

In [ ]:
series1 = (['462809','462643','466315','461735'])
series2 = (['Male','Female','Female','Male'])
series3 = (['No','Yes','Yes','Yes'])
series4 = ([22,38,67,67])
series5 = (['No','Yes','Yes','Yes'])
series6 = (['Healthcare', 'Engineer','Engineer','Lawyer'])
series7 = (['1.0',' ','1.0','0.0'])
series8 = (['Low','Average','Low','High'])
series9 = ([4.0,3.0,1.0,2.0])
series10 = (['Cat_4','Cat_4','Cat_6','Cat_6'])
series11 = (['D','A','B','B'])

data_pandas = pd.DataFrame({'ID':series1,'Gender':series2,'Ever_Married':series3,'Age':series4,'Graduated':series5,'Profession':series6,
                          'Work_Experience':series7,'Spending_Score':series8,'Family_Size':series9,'Var_1':series10,'Segmentation':series11})
data_pandas

       ID  Gender Ever_Married  ...  Family_Size  Var_1 Segmentation
0  462809    Male           No  ...          4.0  Cat_4            D
1  462643  Female          Yes  ...          3.0  Cat_4            A
2  466315  Female          Yes  ...          1.0  Cat_6            B
3  461735    Male          Yes  ...          2.0  Cat_6            B

[4 rows x 11 columns]